name: Generate Contribution Snake
permissions:
  contents: read  # sadece read yeterli
on:
  schedule:
    - cron: "0 */12 * * *" # her 12 saatte bir
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout default branch tüm history ile
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # **tüm commitleri** getir

      # Snake animation
      - name: Generate Contribution Snake
        uses: Platane/snk@v3.4.1
        with:
          github_user_name: cebo54
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark
          branch: main  # default branch’in adı
          token: ${{ secrets.GITHUB_TOKEN }}

      # Push to output branch
      - name: Publish Snake
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
